name: Build and Release

on:
  workflow_dispatch:
    branches: [main]
#  push:
#    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Verify package
        run: mvn clean verify -DskipTests

      - name: Build
        run: mvn clean install

      - name: Package and Test
        run: mvn jacoco:prepare-agent clean test package surefire-report:report jacoco:report -P release

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v{{ github.ref }}
          name: Release {{ github.ref }}
          body: This is a release for {{ github.ref }}

      - name: Upload JAR Assets Separately
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: ${{ github.ref }}-${{ file.basename }}

      - name: Create JaCoCo Report archive
        run: zip -r jacoco.zip target/site/jacoco

      - name: Upload JaCoCo Report archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: jacoco.zip
          asset_name: ${{ github.ref }}.jacoco.zip

      - name: Create SureFire HTML Report archive
        run: zip -r reports.zip target/reports

      - name: Upload SureFire HTML Report archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: reports.zip
          asset_name: ${{ github.ref }}.reports.zip